baseURL = 'http://casahaga.no/'
languageCode = 'nb'
title = 'Casa Haga'
theme = 'PaperMod'

[params]
defaultTheme = "auto"
ShowReadingTime = true

[params.homeInfoParams]
Title = "Velkommen!"
Content = "Her finner du praktisk info om leiligheten, og ting å gjøre i nærheten"
